config/routes.rb
Rails.application.routes.draw do
  root to: "users#splash"

  get "/users/instructors", to: "users#index", as: "instructors"
  get "/users/new", to: "users#new", as: "new_user"
  post "/users", to: "users#create"
  get "/users/:id", to: "users#show", as: "user"
  get "/users/:id/edit", to: "users#edit", as: "edit_user"
  patch "/users/:id", to: "users#update"
  delete "/users/:id", to: "users#destroy", as: "destroy_user"
  post "/users/:id", to: "users#add_instructor", as: "add_instructor"
  post "/users/:id/remove", to: "users#remove_student", as: "remove_student"
  get "/users/:id/follow", to: "users#follow", as: "follow_user"
  post "/users/:id/follow", to: "users#confirm_instructor", as: "confirm_instructor"
  delete "/users/:id/follow", to: "users#deny_instructor", as: "deny_instructor"

  get "/login", to: "sessions#new", as: "new_session"
  get "/logout", to: "sessions#destroy"
  post "/sessions", to: "sessions#create", as: "create_session"

  resources :tweets,          only: [:create, :destroy]

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_friendship

  before_validation :default_values

  validates :email, uniqueness: true, length: { in: 2..150}, presence: true
  validates :first_name, length: { in: 2..50}, presence: true
  validates :last_name, length: { in: 2..75}, presence: true

  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  has_many :tweets, dependent: :destroy

  private
  def default_values
    self.image = "https://ucarecdn.com/1386c488-f2db-4b63-959f-32656a7e35c6/" if self.image == ""
  end

  def self.confirm(params)
    @user = User.where("email ILIKE ?", params[:email]).first
    @user.try(:authenticate, params[:password])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def logged_in_user
    unless current_user
      store_location
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.confirm(user_params)
    if @user
      login(@user)
      flash[:success] = "Successfully logged in."
      redirect_to @user
    else
      flash[:error] = "Incorrect email or password."
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Successfully logged out."
    redirect_to root_path
  end

private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def create
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
      flash[:success] = "tweet created!"
      redirect_to current_user
    else
      flash[:error] = "unable to create tweet"
    end
  end

  def destroy
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.destroy
      flash[:success] = "Tweet has been deleted"
      redirect_to current_user
    else
      flash[:error] = "unable to delete tweet"
    end
  end

  private

    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include AuthHelper

  def splash
    render :splash
  end

  def index
    @user = User.all
    render :instructors
  end

  def new
    @user = User.new
    if current_user != nil
      flash[:notice] = "Already logged in"
      redirect_to current_user
    end
  end

  def create
    set_user
    if @user.save
      login(@user)
      flash[:notice] = "Your account was successfully created! Welcome to HomeRoom!"
      redirect_to @user
    else
      flash[:notice] = "There was a problem creating your account. #{@user.errors.full_messages.join(', ')}."
      redirect_to new_user_path
    end
  end

  def show
    find_user
    if current_user
      @tweets = @user.tweets
      @instructor_tweets = []
      current_user.friends.each do |f|
        f.tweets.each do |g|
          @instructor_tweets.push(g)
        end
      end
    else
      flash[:notice] = "Please sign up to view profile"
      redirect_to new_session_path
    end

  end

  def edit
    find_user
    auth_fail("edit other people's user information!", @user) if !auth_route(@user)
  end

  def update
    find_user
    if auth_route(@user)
      if @user.update(user_params)
        flash[:success] = "Your profile was successfully updated"
        redirect_to @user
      else
        render :edit
      end
    else
      auth_fail("update other people's user information!", @user)
    end
  end

  def destroy
    find_user
    if auth_route(@user)
      @user.destroy
      flash[:success] = "Your account has been deactivated."
      redirect_to root_path
    else
      auth_fail("Your account could not be deactivated.", user_path(@user))
    end
  end

  def follow
    find_user
    auth_fail("see other people's follow requests", @user) if !auth_route(@user)
    if current_user.role == false
      flash[:notice] = "As a student, you do not have follow requests"
      redirect_to current_user
    end
  end

  def add_instructor
    current_user.friend_request(find_user)
    if current_user.save
      redirect_to user_path, notice: "Request was sent to instructor"
    else
      redirect_to user_path, flash[:error] = "There was an error to adding this instructor"
    end
  end

  def confirm_instructor
    find_user
    current_user.accept_request(@user)
    if current_user.save
      redirect_to follow_user_path(current_user), notice: "You have added this student to your class"
    else
      redirect_to user_path, flash[:error] = "There was an error to adding this student"
    end
  end

  def deny_instructor
    if current_user.decline_request(current_user.requested_friends[0])
      redirect_to confirm_instructor_path, notice: "Student was not added"
    else
      redirect_to user_path, flash[:error] = "There was an error removing this student"
    end
  end

  def remove_student
    find_user
    if current_user.remove_friend(@user)
      redirect_to current_user, notice: "Student was removed"
    else
      redirect_to user_path, flash[:error] = "There was an error removing this student"
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :image, :role, :course)
  end

  def set_user
    @user = User.new(user_params)
  end

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: 'alert') do
        concat message
      end)
    end
    nil
  end

end

app/helpers/auth_helper.rb
module AuthHelper

  def auth_route(user)
    current_user != nil && current_user.id == user.id
  end

  def auth_fail(reason_for_failure, redirect_path)
    flash[:error] = "You can't " + reason_for_failure
    redirect_to redirect_path
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def login(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logout
    @current_user = session[:user_id] = nil
  end

  def logged_in?
    if current_user == nil
      redirect_to login_path
    end
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Homeroom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= include_uploadcare_widget_from_cdn version: "2.9.0", min: true %>
  <%= uploadcare_settings %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <script>
  UPLOADCARE_LOCALE = "en";
  UPLOADCARE_TABS = "file url camera facebook gdrive dropbox instagram flickr skydrive";
  UPLOADCARE_PUBLIC_KEY = "714dace727ceee0c4ed9";
  </script>
</head>
<body>
  <div class="col-md-12" id="wrapper">
    <header>
      <div class = "nav-div">
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="col-xs-12 navbar-header" style="padding-left:-10px">
            <div class="col-xs-3 pull-left">
              <a href="/" class="navbar-brand"><img class = "img-responsive" src="http://i.imgur.com/TwxOi2O.png"></a>
            </div>
            <div class="col-xs-9 pull-right">
              <ul class="nav navbar-nav v-align pull-right">
                <% if current_user %>
                <ul class="nav navbar-nav">
                  <li><%= link_to "Home", user_path(current_user)%></li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.first_name.titleize %>'s Profile <span class="glyphicon glyphicon-user pull-right"></span></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "Profile Settings", edit_user_path(current_user) %></li>
                      <% if current_user != nil && current_user.role == true %>
                        <li class="divider"></li>
                        <li><%= link_to "Follow Requests (" + current_user.requested_friends.count.to_s + ")", follow_user_path(current_user) %></li>
                      <% end %>
                      <li class="divider"></li>
                      <li><%= link_to "Log Out", logout_path %></li>
                    </ul>
                  </li>
                </ul>
                <% else %>
                <li><%= link_to "Sign up", new_user_path %></li>
                <li><%= link_to "Log In", new_session_path %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </div>


    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <div class="container">
        <div class="col-md-12">

          <p>// Coded by <%= link_to "Daniel Oh", "https://www.github.com/danieloh91/Homeroom", :target => "_blank" %> [2016] //</p>
        </div>
      </div>
    </footer>
  </div>
</body>
</html>

app/views/tweets/_tweet.html.erb
<li id="tweet-<%= tweet.id %>">
  <span class="content"><%= tweet.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(tweet.created_at) %> ago.
    <% if current_user.role == true %>
      <%= link_to tweet_path(tweet), class: "pull-right", method: :delete do %>
        <i class="glyphicon glyphicon-trash"></i>
      <% end %>
    <% end %>
  </span>
</li>

app/views/tweets/_tweet_form.html.erb
<%= form_for(tweet) do |f| %>
  <div class="field">
    <%= f.text_area :content, size: "79x4", placeholder: "Make an announcement...", maxlength: 140 %>
  </div>
  <br>
  <%= button_to "Post", tweets_path, {class: "ruby-link btn btn-info btn-default btn-md"} %>
<% end %>

app/views/users/_user_form.html.erb
<div class="col-md-4 col-md-offset-4">
  <div class="EditProfile">
    <%= bootstrap_form_for(@user) do |f| %>
      <%= f.text_field :first_name, placeholder: 'First Name' %>
      <%= f.text_field :last_name, placeholder: 'Last Name' %>
      <%= f.email_field :email, placeholder: 'Email' %>
      <%= f.password_field :password, placeholder: 'Password' %>
      <p><strong>Profile Picture</strong></p>
      <%= f.uploadcare_uploader :image, :data => {:images_only => true, :crop => "500x500 minimum", :image_shrink => "500x500", :clearable => true } %>
      <br><br>
      <%= f.form_group :role, label: { text: "Signing up as:" } do %>
        <div class="HideCourses">
          <%= f.radio_button :role, false, label: "Student" %>
        </div>
        <div class="ShowCourses">
          <%= f.radio_button :role, true, label: "Instructor" %>
        </div>
      <% end %>
      <div class="instructor">
        <%= f.select :course, [[nil, nil], ['WDI', "WDI"], ['UXDI', "UXDI"], ['DSI', "DSI"]], { label: "Instructor of:" }, { class: "selectpicker" } %>
      </div>
    <br>
    <div class="FormButtons">
      <%= f.submit @user.new_record? ? "Create Account" : "Update Profile"  %>
      <%= button_to "Cancel", :back, method: :get, :class=>"ruby-link btn btn-info btn-default btn-md" %>
    </div>
    <% end %>
    <br>
  </div>
</div>

app/views/users/edit.html.erb
<h2><strong>Edit Your Profile</strong></h2>
<br><br>

<div class="row">
  <%= render "user_form" %>
</div>

<div class="text-center">
  <% if current_user != nil && current_user.id == @user.id %>
    <div class="row userbuttons">
      <button class="ruby-link btn btn-danger inline btn-primary btn-md inline" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">Deactivate Account</button>
    </div>
    <div class="row">
      <div class="collapse" id="collapseExample">
        <div class="well col-xs-4 col-xs-offset-4">
          <h5 class="inline">
            Are you sure you want to deactivate your account?
          </h5>
          <button class="ruby-link btn-danger btn-primary btn-sm inline">
            <%= link_to "Deactivate", destroy_user_path(@user), method: :delete, :class=>"ruby-link"%>
          </button>
          <%= button_to "Cancel", :back, method: :get, :class=>"ruby-link btn btn-info btn-default btn-md inline" %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br><br>

app/views/users/follow.html.erb
<div class="flash-message-container">
  <%= flash_messages %>
</div>

<div class="row">
  <div class="well col-sm-6 col-sm-offset-3">
    <legend>Follow Requests (<%= current_user.requested_friends.count %>)</legend>
    <div class="col-sm-4 about">
      <div class="col-sm-12">
        <% current_user.requested_friends.each do |f| %>
          <h3><%= f.first_name.titleize %></h3>
          <%= button_to "Confirm", confirm_instructor_path(f), :class=>"ruby-link btn btn-info btn-default btn-md" %>
          <button class="ruby-link btn-danger btn-primary btn-sm inline">
            <%= link_to "Delete Request", deny_instructor_path, method: :delete, :class=>"ruby-link"%>
          </button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/instructors.html.erb
<br>
<br>
<br>
<br>
<br>
<br>

<div class="row">
  <div class="well col-sm-10 col-sm-offset-1">
    <legend>Instructors</legend>
    <div class="col-sm-4 about">
      <div class="col-sm-12">
        <h3>WDI</h3>
        <% @user.each do |f| %>
          <% if f.course == "WDI" && f.role==true %>
            <%= image_tag("#{f.image}", width: "200px", alt: "Profile Picture", :class => "circle_image") %>
            <br>
            <%= link_to f.first_name.titleize + " " + f.last_name.titleize, user_path(f.id) %>
            <br>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-sm-4 about">
      <div class="col-sm-12">
        <h3>UXDI</h3>
        <% @user.each do |f| %>
          <% if f.course == "UXDI" && f.role==true %>
            <%= image_tag("#{f.image}", width: "200px", alt: "Profile Picture", :class => "circle_image") %><br>
            <%= link_to f.first_name.titleize + " " + f.last_name.titleize, user_path(f.id) %><br>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="col-sm-4 about">
      <div class="col-sm-12">
        <h3>DSI</h3>
        <% @user.each do |f| %>
          <% if f.course == "DSI" && f.role==true %>
            <%= image_tag("#{f.image}", width: "200px", alt: "Profile Picture", :class => "circle_image") %><br>
            <%= link_to f.first_name.titleize + " " + f.last_name.titleize, user_path(f.id) %><br>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="flash-message-container">
  <%= flash_messages %>
</div>

<div class="col-md-12">
  <div class="container">
    <h2><strong>Sign Up!</strong></h2>
    <br><br>

    <%= render "user_form" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="flash-message-container">
  <%= flash_messages %>
</div>

<div class="col-md-4 user-info-column">
  <div class="row user-img">
    <%= image_tag("#{@user.image}", width: "200px", height: "200px", alt: "Profile Picture") %>
  </div>
  <h3><%= @user.first_name.titleize %> <%= @user.last_name.titleize %></h3>
  <!-- instructor's page -->
  <% if current_user != nil && current_user.id == @user.id && current_user.role == true %>
    <h3>Instructor of: <%= @user.course %></h3>
    <div class="row">
      <div class="well col-sm-10 col-sm-offset-1">
        <legend>Students</legend>
        <div class="col-sm-12 student-info">
          <% @user.friends.each do |f| %>
            <span><%= link_to image_tag(f.image, width: "50px"), user_path(f) %><br>
            <%= link_to f.first_name.titleize + " " + f.last_name.titleize, user_path(f) %><br></span>
          <% end %>
        </div>
      </div>
    </div>

  <!-- student's page -->
  <% elsif current_user != nil && current_user.id == @user.id && current_user.role == false %>
    <%= @user.email %>
    <br>
    <br>
    <div class="row">
      <div class="well col-sm-12">
        <legend>
          Instructors
          <%= link_to instructors_path do %>
            <i class="glyphicon glyphicon-plus"></i>
          <% end %>
        </legend>
        <div class="col-sm-4 about">
          <div class="col-sm-12">
            <h3>WDI</h3>
            <% @user.friends.each do |f| %>
              <% if f.course == "WDI" && f.role==true %>
                <%= link_to image_tag(f.image, width: "50px"), user_path(f) %><br>
                <%= link_to f.first_name.titleize + " " + f.last_name.titleize, user_path(f) %><br><br>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="col-sm-4 about">
          <div class="col-sm-12">
            <h3>UXDI</h3>
            <% @user.friends.each do |f| %>
            <% if f.course == "UXDI" && f.role==true %>
              <%= link_to image_tag(f.image, width: "50px"), user_path(f) %><br>
              <%= link_to f.first_name.titleize + " " + f.last_name.titleize, user_path(f) %><br><br>
            <% end %>
            <% end %>
          </div>
        </div>
        <div class="col-sm-4 about">
          <div class="col-sm-12">
            <h3>DSI</h3>
            <% @user.friends.each do |f| %>
            <% if f.course == "DSI" && f.role==true %>
              <%= link_to image_tag(f.image, width: "50px"), user_path(f) %><br>
              <%= link_to f.first_name.titleize + " " + f.last_name.titleize, user_path(f) %><br><br>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  <!-- instructor looking at student page -->
  <% elsif current_user != nil && current_user.id != @user.id && current_user.role == true && @user.role == false %>
    <% if current_user.friends_with?(@user) %>
      <%= button_to "Remove Student", remove_student_path, class: "ruby-link btn btn-info btn-danger btn-md" %>
    <% end %>
    <div class="row">
      <div class="well col-sm-12">
        <legend>
          Instructors
        </legend>
        <div class="col-sm-4 about">
          <div class="col-sm-12">
            <h3>WDI</h3>
            <% @user.friends.each do |f| %>
              <% if f.course == "WDI" && f.role==true %>
                <%= link_to image_tag(f.image, width: "50px"), user_path(f) %><br>
                <%= link_to f.first_name.titleize + " " + f.last_name.titleize, user_path(f) %><br><br>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="col-sm-4 about">
          <div class="col-sm-12">
            <h3>UXDI</h3>
            <% @user.friends.each do |f| %>
            <% if f.course == "UXDI" && f.role==true %>
              <%= link_to image_tag(f.image, width: "50px"), user_path(f) %><br>
              <%= link_to f.first_name.titleize + " " + f.last_name.titleize, user_path(f) %><br><br>
            <% end %>
            <% end %>
          </div>
        </div>
        <div class="col-sm-4 about">
          <div class="col-sm-12">
            <h3>DSI</h3>
            <% @user.friends.each do |f| %>
            <% if f.course == "DSI" && f.role==true %>
              <%= link_to image_tag(f.image, width: "50px"), user_path(f) %><br>
              <%= link_to f.first_name.titleize + " " + f.last_name.titleize, user_path(f) %><br><br>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  <!-- student looking at instructor page -->
  <% elsif current_user != nil && current_user.id != @user.id && current_user.role == false && @user.role == true %>
    <% if current_user.friends_with?(@user) == true %>
      <button type="button" name="button" class="followBtn" disabled="disabled">Following</button>
    <% elsif @user.requested_friends.include? current_user %>
      <button type="button" name="button" class="pendingBtn" disabled="disabled">Pending Request</button>
    <% else %>
      <%= button_to "Follow", add_instructor_path, {class: "ruby-link btn btn-info btn-default btn-md"} %>
    <% end %>

  <!-- instructor looking at instructor page -->
  <% elsif current_user != nil && current_user.id != @user.id && current_user.role == true && @user.role == true %>
    <h4>Instructor of: <%= @user.course %></h4>
    <div class="row">
      <div class="well col-sm-10 col-sm-offset-1">
        <legend>Students</legend>
        <div class="col-sm-12 student-info">
          <% @user.friends.each do |f| %>
            <span><%= link_to image_tag(f.image, width: "50px"), user_path(f) %><br>
            <%= link_to f.first_name.titleize + " " + f.last_name.titleize, user_path(f) %><br></span>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<!-- user content section -->

<div class="col-md-7 user-content-column">
  <!-- create post only if current user is instructor -->
  <% if current_user != nil && current_user.id == @user.id && current_user.role == true %>
    <div class="row instructor-tweet">
      <h1>Remind students to:</h1>
      <div class="row">
        <aside class="well col-md-9">
          <section class="tweet_form">
            <%= render './tweets/tweet_form', :tweet => @user.tweets.build %>
          </section>
        </aside>
      </div>
    </div>
  <% end %>

  <!-- instructor -->
  <% if current_user != nil && current_user.id == @user.id && current_user.role == true %>
    <div class="row">
      <div class="col-md-8 col-md-offset-2 user-feed">
        <h3>Announcements (<%= @user.tweets.count %>)</h3>
        <% if @user.tweets.count > 0 %>
          <ol class="tweets">
            <%= render @tweets.order(:created_at).reverse_order %>
          </ol>
        <% end %>
      </div>
    </div>

  <!-- student -->
  <% elsif current_user != nil && current_user.id == @user.id && current_user.role == false %>
    <div class="row">
      <div class="col-md-10 user-feed">
        <h3>Feed</h3>
        <ol class="tweets">
          <% @instructor_tweets.sort_by(&:id).reverse_each do |g| %>
            <li id="tweet-<%= g.id %>">
              <%= image_tag("#{g.user.image}", width: "70px", height: "70px", alt: "Profile Picture") %><br>
              <span class="content"><%= g.content %></span>
              <span class="timestamp">
                Posted <%= time_ago_in_words(g.created_at) %> ago.
              </span>
            </li>
          <% end %>
        </ol>
      </div>
    </div>

  <!-- instructor viewing student page -->
  <% elsif current_user != nil && current_user.id != @user.id && current_user.role == true && @user.role == false %>
    <div class="row">
      <div class="col-md-8 user-feed">
        <h3>Instructors are unable to see student feeds</h3>
      </div>
    </div>

  <!-- student viewing instructor page -->
  <% elsif current_user != nil && current_user.id != @user.id && current_user.role == false && @user.role == true %>
    <% if current_user.friends_with?(@user) %>
      <div class="row">
        <div class="col-md-10 user-feed">
          <h3>Feed</h3>
          <ol class="tweets">
            <% @user.tweets.sort_by(&:id).reverse_each do |g| %>
              <li id="tweet-<%= g.id %>">
                <%= image_tag("#{g.user.image}", width: "70px", height: "70px", alt: "Profile Picture") %><br>
                <span class="content"><%= g.content %></span>
                <span class="timestamp">
                  Posted <%= time_ago_in_words(g.created_at) %> ago.
                </span>
              </li>
            <% end %>
          </ol>
        </div>
      </div>
    <% else %>
      <h3>Feed only available for students</h3>
    <% end %>
  <!-- student looking at student page -->
  <% elsif current_user != nil && current_user.id != @user.id && current_user.role == false && @user.role == false %>
    <div class="row">
      <div class="col-md-8 user-feed">
        <h3>Unable to view feed</h3>
      </div>
    </div>

  <!-- instructor looking at instructor page -->
  <% elsif current_user != nil && current_user.id != @user.id && current_user.role == true && @user.role == true %>
    <div class="row">
      <div class="col-md-8 user-feed">
        <h3>Instructors are unable to see announcements of other instructors</h3>
      </div>
    </div>
  <% else %>
    <h3>Please sign up to view</h3>
    <ul>
      <%= button_to "Sign Up Here", new_user_path, method: :get, :class=>"ruby-link btn btn-info btn-default btn-md" %>
    </ul>
  <% end %>
</div>

app/views/users/splash.html.erb
<div class="jumbotron">
</div>

<div>
  <div class="titleSplashPage">
    <h1 class="titleSplashPage"> HomeRoom: Where students and instructors collaborate online </h1>
    <br>
  </div>
</div>

<div class="row">
  <div class="well col-sm-10 col-sm-offset-1">
    <legend>What you'll find...</legend>
    <div class="col-sm-4 about">
      <img class="img-responsive demo" src="http://i.imgur.com/AV4O5c5.png">
      <div class="col-sm-12">
        <h3>Easy Sign Up</h3>
        <p>Just fill out a couple fields and your profile will be set up</p>
      </div>
    </div>
    <div class="col-sm-4 about">
      <img class="img-responsive demo" src="http://i.imgur.com/b6ENc6V.png"/>
      <div class="col-sm-12">
        <h3>Students</h3>
        <p>Stay up to date with assignments</p>
      </div>
    </div>
    <div class="col-sm-4 about">
      <img class="img-responsive demo" class="demo-stretch" src="http://i.imgur.com/RNowHAH.png"/>
      <div class="col-sm-12">
        <h3>Instructors</h3>
        <p>Update your students on assignments</p>
      </div>
    </div>
  </div>
</div>

<div class="row splashBtn">
  <div>
    <% if current_user != nil && current_user.role == true %>
      <%= button_to "Make an Announcement", user_path(current_user), method: :get, :class=>"ruby-link btn btn-info btn-default btn-md" %>
    <% elsif current_user != nil && current_user.role == false %>
      <%= button_to "Find Instructors", instructors_path, method: :get, :class=>"ruby-link btn btn-info btn-default btn-md" %>
    <% else %>
      <%= button_to "Sign Up Here", new_user_path, method: :get, :class=>"ruby-link btn btn-info btn-default btn-md" %>
    <% end %>
  </div>
</div>